### ISSUE TITLE
Consider support version under v1.6?

### ISSUE THREAD

**Issue by singularitti** [fredrikekre/EnumX.jl#4]
Good package! But may I ask if there is a specific reason that only supports v1.6 and above? I am using this package and my CI tests for v1.6- are failing.

**Comment by fredrikekre** [comment]
When this package was published 1.6 was the LTS release. Note that previous Julia releases are end of life. Any particular reason you want to support old Julia versions?

**Comment by singularitti** [comment]
Some high performance platforms (such as supercomputers funded by gov) are reluctant to update their software. In there, some Julia versions are still below v1.6.

**Comment by fredrikekre** [comment]
The majority of the Julia ecosystem have moved on to not support versions below 1.6 though, so I am surprised that this package would be a problem. Would adding by URL work for you?
```
pkg> add https://github.com/fredrikekre/EnumX.jl.git
```
this only prints a warning, and the only things that is broken on earlier Julia seems to be `show`. If you make a PR I would consider merging it though.
